config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  get "home",  to: "pages#home"
  get "about", to: "pages#about"

  root "pages#home"
  resource :session
  resources :passwords, param: :token
  resources :tasks
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Render dynamic PWA files from app/views/pwa/* (remember to link manifest in application.html.erb)
  # get "manifest" => "rails/pwa#manifest", as: :pwa_manifest
  # get "service-worker" => "rails/pwa#service_worker", as: :pwa_service_worker

  # Defines the root path route ("/")
end

app/views/shared/_flash.html.erb
<% flash.each do |key, value| %>
  <div data-controller="flash" 
      class="w-full shadow-md flex justify-between p-3 rounded-md <%= flash_style(key) %> gap-2" role="alert">

    <div aria-hidden="true" class="flex items-start flex-none">
      <%= lucide_icon('circle-check') %> 
    </div>

    <div class="flex flex-col items-start flex-1">
      <h5 class="font-medium leading-none mbe-1">hey!</h5>
      <p id="notice">    
        <%= value %>
      </p>
    </div>
          
    <button data-action="flash#dismiss" type="button" 
            class="flex items-center text-gray-300 hover:text-green-600 transition-all">
      <%= lucide_icon('x') %>
    </button>
  </div>
<% end %>

app/views/shared/_navbar.html.erb
<!-- Links de navegação desktop -->

<nav data-controller="mobile-menu" class="w-full px-2 bg-white/30 dark:bg-stone-800/30 backdrop-blur-lg 
     dark:border-stone-700 drop-shadow-md border-b-[1px] rounded-b-xl md:rounded-none 
     border-white mb-12 sticky top-0 z-20">

  <div class="px-2 max-w-7xl mx-auto sm:px-4 lg:px-8">
    <div class="relative flex h-20 items-center justify-between">
      <div class="flex flex-1 items-center justify-between sm:items-stretch sm:justify-start">
        <div class="flex shrink-0 items-center">
          <span class="shadow-md overflow-hidden block"><%= image_tag('planner_logo.png', class: "h-12") %></span> 
        </div>
        <div class="hidden md:ml-6 md:block">
          <div class="flex space-x-4">
            <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
            <% nav_items.each do | item | %>
              <%= link_to(item[:page], item[:href], class: nav_class(item[:href]), aria: { current: aria(item[:href])}) %>
            <% end %>
          </div>
        </div>
      </div>

      <% if authenticated? %>
        <div class="hidden md:block">
          <div class="ml-4 flex items-center md:ml-6">
            <!-- Profile  -->
            <div class="hidden relative ml-3 lg:flex items-center">
              <div class="shrink-0">
                <%= lucide_icon "user", class: "text-gray-700 dark:text-gray-400 h-6 w-6" %>
              </div>
              <div class="ml-3">
                <div class="text-sm font-medium text-gray-700 dark:text-gray-400"><%= Current.user.email_address %></div>
              </div>
            </div>

            <div class="relative ml-3 flex items-center">
              <%= button_to session_path, class: 'group inline-flex w-full gap-3 rounded-md p-3 text-base 
                  font-medium dark:text-gray-400 hover:bg-stone-500 hover:text-white transition-all duration-300', method: :delete do %>

                <%= lucide_icon 'log-out', class: "group-hover:text-rose-500 transition-all duration-300" %> 
                <span class="hidden lg:inline-flex">Log out</span>
              <% end %>
            </div>
          </div>
        </div>
      <% else %>
        <div class="hidden md:block">
          <div class="ml-4 flex items-center md:ml-6">
            <div class="relative ml-3">
              <div>
              </div>
              <%= button_to new_session_path, class: 'group inline-flex w-full gap-3 rounded-md p-3 text-base font-medium text-gray-700 dark:text-gray-400 
                  hover:bg-stone-500 hover:text-white transition-all duration-300', method: :get do %>

                <%= lucide_icon 'log-in', class: "group-hover:text-green-500 transition-all duration-300"%>
                <span class="hidden lg:inline-flex">Log in</span>
              <% end %>
            </div>
          </div>
        </div>
      <% end %>

      <div class="flex md:hidden">
        <!-- Mobile menu button -->
        <button type="button" 
                data-action="click->mobile-menu#toggleMenu keydown.esc->mobile-menu#closeMenu 
                resize@window->mobile-menu#closeMenu" 
                class="relative inline-flex items-center justify-center rounded-md 
                bg-stone-500 p-2 hover:bg-stone-600 hover:text-white focus:ring
                focus:ring-stone-400 focus:bg-stone-600 focus:outline-none 
                dark:focus:bg-stone-600 focus:text-gray-100 transition-all duration-300" 
                aria-controls="mobile-menu" aria-expanded="false">

          <span class="absolute -inset-0.5"></span>
          <span class="sr-only">Open main menu</span>
          <!-- Menu open: "hidden", Menu closed: "block" -->
          <svg data-mobile-menu-target="btnOpen" class="block size-6 text-gray-200 transition-all" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M3.75 6.75h16.5M3.75 12h16.5m-16.5 5.25h16.5" />
          </svg>
          <!-- Menu open: "block", Menu closed: "hidden" -->
          <svg data-mobile-menu-target="btnClose" class="hidden size-6 transition-all" fill="none" viewBox="0 0 24 24" stroke-width="1.5" stroke="currentColor" aria-hidden="true" data-slot="icon">
            <path stroke-linecap="round" stroke-linejoin="round" d="M6 18 18 6M6 6l12 12" />
          </svg>
        </button>
      </div>

    </div>
  </div>

  <!-- Mobile menu, show/hide based on menu state. -->
  <div data-mobile-menu-target="menu" class="md:hidden flex-col" id="mobile-menu">
    <div class="space-y-1 px-2 py-2 sm:px-3">
      <!-- Current: "bg-gray-900 text-white", Default: "text-gray-300 hover:bg-gray-700 hover:text-white" -->
      <% nav_items.each do | item | %>
        <%= link_to(item[:page], item[:href], class: nav_class_mobile(item[:href]), aria: { current: aria(item[:href])}) %>
      <% end %>
    </div>

    <% if authenticated? %>
      <div class="border-t border-gray-700">
        <div class="flex items-center px-5 py-3">
          <div class="shrink-0">
            <%= lucide_icon "user", class: "text-gray-700 dark:text-gray-400 h-6 w-6" %>
          </div>
          <div class="ml-3">
            <div class="text-sm font-medium text-gray-700 dark:text-gray-400"><%= Current.user.email_address %></div>
          </div>          
        </div>

        <div class="mt-3 space-y-1 px-2">          
          <%= button_to session_path, class: 'group inline-flex w-full gap-3 mb-3 rounded-md p-3 text-base 
              font-medium text-gray-700 dark:text-gray-400 hover:bg-stone-500 hover:text-white',
              method: :delete do %>

            <%= lucide_icon 'log-out', class: "group-hover:text-rose-500 transition-all"  %> Log out
          <% end %>
        </div>
      </div>
    <% else %>
      <div class="border-t border-gray-700 pb-3 py-4">
        <div class="mt-3 space-y-1 px-2">
          <%= button_to new_session_path, class: 'group inline-flex w-full gap-3 mb-3 rounded-md p-3 text-base 
              font-medium text-gray-700 dark:text-gray-400 hover:bg-stone-500 hover:text-white',
              method: :get do %>

            <%= lucide_icon 'log-in', class: "group-hover:text-green-500 transition-all "%> Log in
          <% end %>     
        
          <%# link_to 'Sign up', new_registration_path, 
              class: 'font-semibold text-gray-100  duration-200 
              ease-in-out hover:text-yellow-700' %>
        </div>
      </div>
    <% end %>
  </div>
</nav>